language: csharp  
sudo: required  
dist: xenial  
env:  
  - CLI_VERSION=latest
mono:  
  - 5.18.0
dotnet:  2.2.103
os:  
  - linux
branches:  
  only:
    - master
    - /.*/
before_script:
- chmod +x ./build.linux.sh
before_install:
  - sudo apt install nuget
script:  
  - ./build.linux.sh
