language: csharp  
sudo: required  
dist: xenial  
env:  
  - CLI_VERSION=latest
mono: latest
dotnet:  2.2.401
os:  
  - linux
branches:  
  only:
    - master
    - /.*/
before_script:
- chmod +x ./build.sh
before_install:
  - sudo apt install nuget
script:  
  - ./build.sh
